options:
    prefix: <##AB2330>&lᴇᴢʟᴀᴠᴀʀɪꜱɪɴɢ ≫<##A95F66>


every 4 minute:
    loop all players in world "lavarise":
        if loop-player's gamemode is survival:
            give 64 of dirt to loop-players	

on drop:
    if player is not op:
        if player's world is "world":
            cancel event

on inventory open:
    if player is not op:
        if player's world is "world":
            if {gamevotetime} is false:
                cancel event

on death of player:
    if {servergame} is "pvp":
        if victim is wearing any armor:
            if victim is in world "lavarise":
                make console execute command "/ta add %attacker% 100"

every 5 minutes:
    {servergame} is "pvp":
        loop all players:
            if loop-player's gamemode is survival:
                if loop-player is in world "lavarise":
                    make console execute command "/ta add %loop-player% 10"
                    send "&aRecieved 25 tokens for surviving!" to loop-player

every 8 seconds:
    if {gamemode} is "random":
        loop all players:
            if loop-player's gamemode is survival:
                if loop-player is in world "lavarise":
                    add 4 of (random item out of all items) to inventory of loop-player

on right click:
    player's tool is tnt
    {servergame} is not "pvp"
    cancel event

on block break of any leaves:
    chance of 25%:
        drop 1 apple

on block break of coal ore:
    chance of 80%:
        drop 1 flint

on block break of iron ore:
    chance of 80%:
        drop 1 feather

on block place of bookshelf or enchanting table or anvil or grindstone:
    if {servergame} is not "pvp":
        set {antibreak::%event-block%} to player


on block break of bookshelf or enchanting table or anvil or grindstone:
    if {antibreak::%event-block%} is not player:
        if {servergame} is not "pvp":
            cancel event
            send "&0[&cezLavaRising&0] Only %{antibreak::%event-block%}% can break this block!" to player

on drop:
    if event-item is enchanted book:
        wait 5 seconds
        delete event-dropped item

every 0.75 seconds:
    {servergame} is "pvp"
    if {gamemode} is "void":
        loop all players:
            if loop-player's y coordinate is below {y} - 6:
                if loop-player's gamemode is survival:
                    if loop-player's world is "lavarise":
                        damage loop-player by 2.5 hearts
                        send title "You are too low" to loop-player for 1.75 seconds
                        stop
    else:
        loop all players:
            if loop-player's y coordinate is below {y} - 5:
                if loop-player's gamemode is survival:
                    if loop-player's world is "lavarise":
                        damage loop-player by 2 hearts
                        send title "You are under lava" to loop-player for 1.75 seconds
                        stop
            if loop-player's y coordinate is below {y} - 30:
                if loop-player's gamemode is survival:
                    if loop-player's world is "lavarise":
                        damage loop-player by 10 hearts
                        send title "You are TOO LOW under lava" to loop-player for 1.75 seconds
                        stop

on portal:
    if player is not op:
        cancel event

on place of tnt:
    {gamemode} is "chaos"
    set event-block to air
    spawn primed tnt at event-location

on craft:
    if event-item is "minecart with tnt" parsed as item:
        cancel event
        send "&6[&8&l&oThunderhead&6 -> &cme&6] &f&oSorry, but I won't let you craft that." to player
        close player's inventory

every 2 seconds:
    {gamemode} is "acid"
    loop all players:
        if loop-player is in world "lavarise":
            if block at loop-player is water:
                apply poison 3 to loop-player for 3 seconds
                apply wither 3 to loop-player for 3 seconds
                damage loop-player by 1 heart

on craft:
    if event-item is "shield" parsed as item:
        if {gamemode} is "bull" or "acid" or "ironage":
            cancel event
            send "&6[&8&l&oThunderhead&6 -> &cme&6] &f&oSorry, but I won't let you craft that. At least not on this mode." to player
            close player's inventory
on shoot:
    shooter is player
    if {gamemode} is "bull":
        cancel event
        send "&6[&8&l&oThunderhead&6 -> &cme&6] &f&oSorry, but I won't let you do that. At least not on this mode." to shooter


on damage:
    if {servergame} is not "pvp":
        if victim is in world "lavarise":
            if {gamemode} is not "lucky":
                cancel event

on damage:
    if attacker is "tnt":
        reduce damage by 50%

on break of iron ore:
    clear drops
    if level of fortune of tool is 4:
        drop 5 iron ingot
        stop
    if level of fortune of tool is 3:
        drop 4 iron ingot
        stop
    if level of fortune of tool is 2:
        drop 3 iron ingot
        stop
    if level of fortune of tool is 1:
        drop 2 iron ingot
        stop
    drop iron ingot

on break of gold ore:
    clear drops
    clear drops
    if level of fortune of tool is 4:
        drop 5 gold ingot
        stop
    if level of fortune of tool is 3:
        drop 4 gold ingot
        stop
    if level of fortune of tool is 2:
        drop 3 gold ingot
        stop
    if level of fortune of tool is 1:
        drop 2 gold ingot
        stop
    drop gold ingot


on resurrect attempt:
    wait 5 ticks
    remove fire resistance from player's active potion effects

on consume:
    wait 5 ticks
    remove fire resistance from player's active potion effects

command /suffix [<text>]:
    permission: ezlavarising.premium
    trigger:
        if arg-1 is not set:
            send "{@prefix} Please provide a suffix via /suffix (TEXT)"
        else:
            set {_text} to arg-1
            replace all " " in {_text} with ""
            if length of {_text} is less than 24:
                make console execute command "/lp user %player% meta setsuffix 100 ""&c&l%{_text}%"""


command /rename [<text>]:
    permission: ezlavarising.premium
    permission message: &6[&8&l&oThunderhead&6 -> &cme&6] &f&oSorry, but you can't do that.
    trigger:
        if arg-1 is set:
            if player's tool is not air:
                set name of player's tool to "&r%colored arg-1%"
                send "{@prefix} Successfully renamed!" to player
                play sound "entity.player.levelup" at volume 1 at pitch 1.2 to player

on join:
    create bossbar titled "&c&ldiscord.gg/pDARVhStJZ" and id "joined::%uuid of player%" for player with progress 100
    wait 10 ticks
    loop 100 times:
        set {_boss} to value of bossbar "joined::%uuid of player%"
        remove 1 from {_boss}
        set bossbar "joined::%uuid of player%" value to {_boss}
        wait 100 days


at 18:00:
	set time to 7:00
